apiVersion: v1
kind: Service
metadata:
  name: coordinator
spec:
  selector:
    type: coordinator
  ports:
  - name: http-port
    protocol: TCP
    port: 8091
    targetPort: 8091
---
apiVersion: v1
kind: Service
metadata:
  name: worker
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    type: worker
---
apiVersion: v1
kind: Service
metadata:
  name: sql-proxy
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    type: sql-proxy

