apiVersion: v1
kind: Service
metadata:
  name: coordinator
spec:
  selector:
    type: coordinator
  ports:
  - name: http-port
    protocol: TCP
    port: 8091
    targetPort: 8091
---
apiVersion: v1
kind: Service
metadata:
  name: worker
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    type: worker
---
apiVersion: v1
kind: Service
metadata:
  name: sql-proxy
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    type: sql-proxy
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    type: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
spec:
  defaultBackend:
    service:
      name: frontend
      port:
        number: 80
  rules:
  - http:
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: frontend
              port:
                number: 80
